
name: unittests

on: [push, pull_request]

jobs:
    unittests:
        name: '[PHP ${{ matrix.php-version }} | Flow ${{ matrix.flow-version }}] Unit Tests'
        runs-on: ubuntu-latest
        #    services:
        #      mariadb:
        #        image: mariadb:10.2
        #        env:
        #          MYSQL_USER: neos
        #          MYSQL_PASSWORD: neos
        #          MYSQL_DATABASE: flow_functional_testing
        #          MYSQL_ROOT_PASSWORD: neos
        #        ports:
        #          - 3306/tcp
        #        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        strategy:
            fail-fast: false
            matrix:
                php-version: [7.4, 8.2]
                flow-version: [7.3, 8.3]

                exclude:
                    # Disable Flow 8.3 on PHP 7, as 8.0 is required
                    - php-version: 7.4
                      flow-version: 8.3

        env:
            FLOW_CONTEXT: Testing/Unit
            FLOW_DIST_FOLDER: flow-base-distribution

        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions:  mbstring, xml, json, zlib, iconv, intl, pdo_sqlite, mysql
                  ini-values: opcache.fast_shutdown=0

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.composer/cache
                  key: php-${{ matrix.php-version }}-flow-${{ matrix.flow-version }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: |
                      php-${{ matrix.php-version }}-flow-${{ matrix.flow-version }}-composer-
                      php-${{ matrix.php-version }}-flow-
            - name: Install composer dependencies
              run: composer create-project neos/flow-base-distribution ${{ env.FLOW_DIST_FOLDER }} --prefer-dist --no-progress --no-install "^${{ matrix.flow-version }}"

            - name: Allow neos composer plugin
              run: composer config --no-plugins allow-plugins.neos/composer-plugin true
              working-directory: ${{ env.FLOW_DIST_FOLDER }}

            - name: Require behat in compatible version
              run: composer require --dev --no-update "neos/behat:@dev"
              working-directory: ${{ env.FLOW_DIST_FOLDER }}

            - name: Install project
              run: composer install
              working-directory: ${{ env.FLOW_DIST_FOLDER }}

            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  path: ${{ env.FLOW_DIST_FOLDER }}/DistributionPackages/Netlogix.Migrations.JobQueue

            - name: Install netlogix/migrations-jobqueue
              run: composer require netlogix/migrations-jobqueue:@dev
              working-directory: ${{ env.FLOW_DIST_FOLDER }}

            - name: Run tests
              run: bin/phpunit -c DistributionPackages/Netlogix.Migrations.JobQueue/phpunit.xml.dist --bootstrap "Build/BuildEssentials/PhpUnit/UnitTestBootstrap.php"
              working-directory: ${{ env.FLOW_DIST_FOLDER }}
